### ISSUE TITLE
Difficulty running the example on stm32f013xx-hal create

### ISSUE THREAD

**Issue by ninjasource** [japaric/enc28j60#3]
Hi, thanks for this library and your great blog post about it. However, I am having trouble building the example. This does not work on stable "cargo build --example enc28j60" and there are no instructions on what feature flags to pass to get it to work or if it works on stable at all anyway. Any form of information, even if it seems verbose and unnecessary would be helpful.

**Comment by ninjasource** [comment]
Jnet seems to be the problem. Unfortunately, there is no way for me to log an issue with jnet so you may not know that others are struggling to build it for lack of instructions. I would gladly update your README.md file once I know how to compile these libraries.

**Comment by japaric** [comment]
The stm32f103xx-hal is slated for deprecation and the jnet API is unstable (in the "not going to be freezed anytime soon" sense). There are some examples in https://github.com/japaric/jnet/tree/master/firmware but I can't provide you, or anyone, with support on how to use jnet at the moment (as the jnet README says).

**Comment by ninjasource** [comment]
Thanks Jorge, I found that earlier this week. On the topic of support, I understand that you want the freedom to change the jnet library at will and answering questions about it may seem pointless since you intend to change it all anyway. However, from my own experience with writing libraries, the issues people raise are rarely an attack on the software but rather an indication of the areas the people find difficult to work with. This change in perspective can be a very valuable source of information for you. Anyway, keep up the good work!
